# encoding: UTF-8

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Categorías
aminas = Categoria.find_or_create_by(nombre: 'Aminas')
cloro = Categoria.find_or_create_by(nombre: 'Cloro granular y en tabletas')
mezcla_solventes = Categoria.find_or_create_by(nombre: 'Mezcla de Solventes')
polimeros = Categoria.find_or_create_by(nombre: 'Polímeros acrílicos')
gases = Categoria.find_or_create_by(nombre: 'Gases Refrigerantes')

# Productos de categoria
Producto.find_or_create_by(nombre: 'MEZCLA ANHIDRO – ACETATO DE ETILO (80-20)', categoria: mezcla_solventes)
Producto.find_or_create_by(nombre: 'MEZCLA ANHIDRO – ACETATO N PROPILO (80-20)', categoria: mezcla_solventes)
Producto.find_or_create_by(nombre: 'MEZCLA IPA – ACETATO DE ETILO (80-20)', categoria: mezcla_solventes)
Producto.find_or_create_by(nombre: 'MEZCLA IPA – ACETATO N PROPILO (80-20)', categoria: mezcla_solventes)
Producto.find_or_create_by(nombre: 'MEZCLA N-PROPANOL – ACETATO DE ETILO (80-20)', categoria: mezcla_solventes)
Producto.find_or_create_by(nombre: 'MEZCLA N-PROPANOL - ACETATO N PROPILO (80-20)', categoria: mezcla_solventes)

Producto.find_or_create_by(nombre: 'R-22', categoria: gases)
Producto.find_or_create_by(nombre: 'R-134 A', categoria: gases)
Producto.find_or_create_by(nombre: 'R-404 A', categoria: gases)
Producto.find_or_create_by(nombre: 'R-407 C', categoria: gases)
Producto.find_or_create_by(nombre: 'R-410 A', categoria: gases)
Producto.find_or_create_by(nombre: 'R-507', categoria: gases)
Producto.find_or_create_by(nombre: 'ICEON MO 99', categoria: gases)

Producto.find_or_create_by(nombre: 'Thyon SF-2 (SF15) ', categoria: polimeros)
Producto.find_or_create_by(nombre: 'Thyon HF-4 (HF18)', categoria: polimeros)
Producto.find_or_create_by(nombre: 'Thyon FC-56', categoria: polimeros)
Producto.find_or_create_by(nombre: 'Thyon SR-650', categoria: polimeros)
Producto.find_or_create_by(nombre: 'Thyosil E-189', categoria: polimeros)
Producto.find_or_create_by(nombre: 'Thyosil E-190 (polímero acrílico estirenado)', categoria: polimeros)
Producto.find_or_create_by(nombre: 'Thyosil E-193', categoria: polimeros)
Producto.find_or_create_by(nombre: 'Thyosil E-195', categoria: polimeros)
Producto.find_or_create_by(nombre: 'Thyosil E-203', categoria: polimeros)
Producto.find_or_create_by(nombre: 'Thyosil Q-201 (antiespumante plantas papel y pastas)', categoria: polimeros)
Producto.find_or_create_by(nombre: 'Thyosil Q-202 (antiespumante)', categoria: polimeros)
Producto.find_or_create_by(nombre: 'Thyosil Q-300 (cationico bajo peso molecular)', categoria: polimeros)
Producto.find_or_create_by(nombre: 'Polacril D-40', categoria: polimeros)
Producto.find_or_create_by(nombre: 'Polacril HV', categoria: polimeros)
Producto.find_or_create_by(nombre: 'Polacril 930', categoria: polimeros)
Producto.find_or_create_by(nombre: 'Polacril AT 960', categoria: polimeros)
Producto.find_or_create_by(nombre: 'Polacril AT 990', categoria: polimeros)

Producto.find_or_create_by(nombre: 'Dicloro 62% China (granulado 10-30, grueso) (Dicloroisocianurato de sodio)', categoria: cloro)
Producto.find_or_create_by(nombre: 'Dicloro 62% China (granulado 20-40, fino) ', categoria: cloro)
Producto.find_or_create_by(nombre: 'Dicloro 62 % China (granulado)  ', categoria: cloro)
Producto.find_or_create_by(nombre: 'Tricloro 90% China (tabletas) (Tricloroisocianurato de Sodio)', categoria: cloro)
Producto.find_or_create_by(nombre: 'Tripleacion tabletas', categoria: cloro)
Producto.find_or_create_by(nombre: 'Hipoclorito de Calcio (granulado, mín. 65%) HTH ', categoria: cloro)
Producto.find_or_create_by(nombre: 'Hipoclorito de Calcio (granulado, mín. 65%) Hypocal', categoria: cloro)
Producto.find_or_create_by(nombre: 'Hipoclorito de Calcio (tabletas 200 g) Hypocal', categoria: cloro)

Producto.find_or_create_by(nombre: 'Monoetanolamina (MEA) ', categoria: aminas)
Producto.find_or_create_by(nombre: 'Dietanolamina 85% (DEA 85%) ', categoria: aminas)
Producto.find_or_create_by(nombre: 'Dietanolamina 99% (DEA 99%). ', categoria: aminas)
Producto.find_or_create_by(nombre: 'Trietanolamina 85%- (TEA 85%+Agua 15%) ', categoria: aminas)
Producto.find_or_create_by(nombre: 'Trietanolamina  99% (TEA 99%)', categoria: aminas)




# Productos
Producto.find_or_create_by(nombre: 'Aceite Mineral o Vaselina líquida')
Producto.find_or_create_by(nombre: 'Acesulfame K')
Producto.find_or_create_by(nombre: 'Acetato Butyl Carbitol')
Producto.find_or_create_by(nombre: 'Acetato Butyl Glicol')
Producto.find_or_create_by(nombre: 'Acetato de Butilo')
Producto.find_or_create_by(nombre: 'Acetato de Etilo') 
Producto.find_or_create_by(nombre: 'Acetato N-propilo') 
Producto.find_or_create_by(nombre: 'Acetona')
Producto.find_or_create_by(nombre: 'Acido Cítrico Anhidro') 
Producto.find_or_create_by(nombre: 'Acido Cítrico Monohidratado')
Producto.find_or_create_by(nombre: 'Acido Dodecil benceno Sulfónico 90%')
Producto.find_or_create_by(nombre: 'Acido Dodecil benceno Sulfónico 96%') 
Producto.find_or_create_by(nombre: 'Acido Fórmico.') 
Producto.find_or_create_by(nombre: 'Acido Fosfórico técnico 75%')
Producto.find_or_create_by(nombre: 'Acido Fosfórico técnico 85%') 
Producto.find_or_create_by(nombre: 'Aguarrás Mineral')
Producto.find_or_create_by(nombre: 'Alcohol Anhidro Cereal 99,9%') 
Producto.find_or_create_by(nombre: 'Alcohol Anhidro Melaza 99,9%') 
Producto.find_or_create_by(nombre: 'Alcohol Desnaturalizado c/IPA') 
Producto.find_or_create_by(nombre: 'Alcohol Etílico 96°ª') 
Producto.find_or_create_by(nombre: 'Anhidro Ftálico (PA)')
Producto.find_or_create_by(nombre: 'Aromático Pesado (High Flash)')
Producto.find_or_create_by(nombre: 'Bencina Blanca')
Producto.find_or_create_by(nombre: 'Butanol')
Producto.find_or_create_by(nombre: 'Butyl Carbitol')
Producto.find_or_create_by(nombre: 'Butyl Cellosolve') 
Producto.find_or_create_by(nombre: 'Carbitol (Ethyl Diglicol)')
Producto.find_or_create_by(nombre: 'Cellosolve') 
Producto.find_or_create_by(nombre: 'Ciclohexano') 
Producto.find_or_create_by(nombre: 'Ciclohexanona') 
Producto.find_or_create_by(nombre: 'Cloropreno marca DENKA: A90') 
Producto.find_or_create_by(nombre: 'Cloropreno marca DENKA: A100')
Producto.find_or_create_by(nombre: 'Cloropreno marca DENKA: M130H')
Producto.find_or_create_by(nombre: 'Cloruro de Calcio 74% China')
Producto.find_or_create_by(nombre: 'Cloruro de Metileno') 
Producto.find_or_create_by(nombre: 'Diacetona Alcohol (DAA)')  
Producto.find_or_create_by(nombre: 'Di Butyl Ftalato (DBP)')
Producto.find_or_create_by(nombre: 'Di Octil Ftalato (DOP)')
Producto.find_or_create_by(nombre: 'Dietilenglicol (DEG)')
Producto.find_or_create_by(nombre: 'Dipropilenglicol (DPG)') 
Producto.find_or_create_by(nombre: 'DMF (Di Metil Formamida)') 
Producto.find_or_create_by(nombre: 'Dowanol DPM (Solvenom DPM)') 
Producto.find_or_create_by(nombre: 'Dowanol PM  (Solvenom PM)') 
Producto.find_or_create_by(nombre: 'Dowanol PMA (Solvenom PMA)') 
Producto.find_or_create_by(nombre: 'Dowanol PNB')
Producto.find_or_create_by(nombre: 'Dowanol PNP')
Producto.find_or_create_by(nombre: 'Etoxy Propanol (EP)') 
Producto.find_or_create_by(nombre: 'Exxal 8 / Alcohol Isooctílico')
Producto.find_or_create_by(nombre: 'Exxsol D-40  / Renosol D-40')
Producto.find_or_create_by(nombre: 'Exxsol D-60  / Renosol D-60')
Producto.find_or_create_by(nombre: 'Exxsol D-80  / Renosol D-80')
Producto.find_or_create_by(nombre: 'Exxsol DSP 75/95 / Renosol DSP 75/95')
Producto.find_or_create_by(nombre: 'Isobutanol (IBA)   (Alcohol Isobutílico)')
Producto.find_or_create_by(nombre: 'Isopropanol - IPA (Alcohol Isopropílico)')
Producto.find_or_create_by(nombre: 'Lauril éter sulfato sodio 70% - Europa')
Producto.find_or_create_by(nombre: 'Lauril éter sulfato sodio 70%  - Coreav')
Producto.find_or_create_by(nombre: 'MDI')
Producto.find_or_create_by(nombre: 'Metabisulfito Sodio food grade') 
Producto.find_or_create_by(nombre: 'Metanol  (Alcohol Metílico)')
Producto.find_or_create_by(nombre: 'Metasilicato Sodio Anhidro Oxy-USA') 
Producto.find_or_create_by(nombre: 'Metasilicato Sodio Penta') 
Producto.find_or_create_by(nombre: 'Metil carbitol')
Producto.find_or_create_by(nombre: 'Metil Etil Cetona (MEK)') 
Producto.find_or_create_by(nombre: 'Metil Isobutyl Cetona (MIBK)')
Producto.find_or_create_by(nombre: 'Monoetilenglicol')  
Producto.find_or_create_by(nombre: 'Monopersulfato de Potasio / Oxone')
Producto.find_or_create_by(nombre: 'N-Propanol   (Alcohol n-Propílico)')
Producto.find_or_create_by(nombre: 'Oxido de Zinc sello de oro') 
Producto.find_or_create_by(nombre: 'Parafina Refinada 56/58 D (bajo 0,5% aceite)') 
Producto.find_or_create_by(nombre: 'Parafina Refinada 58/60 D (bajo 0,5% aceite)') 
Producto.find_or_create_by(nombre: 'Parafina Refinada 60/62 D (bajo 0,5% aceite)') 
Producto.find_or_create_by(nombre: 'Parafina Refinada 66/68 D (bajo 0,5% aceite)')
Producto.find_or_create_by(nombre: 'Parafina Clorada 52%') 
Producto.find_or_create_by(nombre: 'Pentaeritritol  95% min.') 
Producto.find_or_create_by(nombre: 'Pentaeritritol  98% min.') 
Producto.find_or_create_by(nombre: 'Percloroetileno') 
Producto.find_or_create_by(nombre: 'Permanganato de Potasio') 
Producto.find_or_create_by(nombre: 'Poliol')   
Producto.find_or_create_by(nombre: 'Potasa Caustica Oxy (USA) o de Corea') 
Producto.find_or_create_by(nombre: 'Propilenglicol USP')
Producto.find_or_create_by(nombre: 'Soda Caustica escama')
Producto.find_or_create_by(nombre: 'Soda Caustica microperla') 
Producto.find_or_create_by(nombre: 'Solvesso 150 / Solreno 150')
Producto.find_or_create_by(nombre: 'Solvesso 200 / Solreno 200')
Producto.find_or_create_by(nombre: 'TDI 80-20  (Di isocianato de Tolueno)')
Producto.find_or_create_by(nombre: 'Tetrahidrofurano (THF)')
Producto.find_or_create_by(nombre: 'Toluol grado Nitración / Tolueno')
Producto.find_or_create_by(nombre: 'Tricloroetileno')
Producto.find_or_create_by(nombre: 'Tripolifostato Sodio food grade') 
Producto.find_or_create_by(nombre: 'Tripolifostato Sodio grado técnico')  
Producto.find_or_create_by(nombre: 'Ucar Filmer IBT (agente coalescente)')
Producto.find_or_create_by(nombre: 'VAM (Vinil Acetato monómero)')
Producto.find_or_create_by(nombre: 'Xilol Nacional')  
Producto.find_or_create_by(nombre: 'Xilol grado Nitración (importado)')
